export default {
    ONLOAD_MYINFO: "ONLOAD_MYINFO",
    ONLOAD_CONTACT_LIST: "ONLOAD_CONTACT_LIST",
    ADD_CONTACT_LIST: "ADD_CONTACT_LIST",
    ONLOAD_GROUP_LIST: "ONLOAD_GROUP_LIST",
    ADD_GROUP: "ADD_GROUP",
    ONLOAD_GROUP_MEMBER_LIST: "ONLOAD_GROUP_MEMBER_LIST",
    ADD_GROUP_MEMBER_LIST: "ADD_GROUP_MEMBER_LIST",
    ONLOAD_NEW_FRIEND: "ONLOAD_NEW_FRIEND",
    ADD_NEW_FRIEND: "ADD_NEW_FRIEND",
    REVIEW_NEW_FRIEND: "REVIEW_NEW_FRIEND",
}
